name: run-tests

on:
    push:
    pull_request:

jobs:
    run-tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [7.4, 8.0, 8.1]
                laravel: [8.*, 9.*]
                dependency-version: [prefer-lowest, prefer-stable]
                include:
                    -   laravel: 8.*
                        testbench: 6.*
                    -   laravel: 9.*
                        testbench: 7.*
                exclude:
                    -   php: 8.1
                        laravel: 8.*
                        dependency-version: prefer-lowest
                    -   php: 8.0
                        laravel: 8.*
                        dependency-version: prefer-lowest
                    -   php: 7.4
                        laravel: 9.*

        name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.dependency-version }}

        steps:
            -   name: Update apt
                run: sudo apt-get update --fix-missing

            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: xdebug
                    extensions: yaml

            -   name: Install dependencies
                run: |
                    composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

            -   name: Execute tests
                run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
