name: run-linting

on:
    push:
    pull_request:

jobs:
    run-linting:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: 8.0

            - name: Install dependencies
              run: composer install --prefer-dist --no-interaction --no-suggest

            - name: Execute linting
              run: |
                vendor/bin/php-cs-fixer fix --dry-run
                vendor/bin/phpcs --colors --report-full
